// Each app's orivon.json is what the consent dialog renders. A manifest that
// does not parse, or that omits a field, is a dialog that cannot be shown --
// and consent is read before any of the app's code runs, so the failure is
// the app not starting at all. `assets` is the one field it must NOT carry:
// prepare generates it from the built tree (src/declare.ts).
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { recipeDir } from '../src/paths.ts'
import { recipesOrReport, report } from './lib.ts'

const REQUIRED = ['orivonApiVersion', 'id', 'name', 'version', 'entry', 'capabilities']

const problems: string[] = []

for (const recipe of await recipesOrReport('check:manifest')) {
  const path = join(recipeDir(recipe.id), recipe.manifest)
  let manifest: Record<string, unknown>
  try {
    manifest = JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>
  } catch (error) {
    problems.push(`apps/${recipe.id}/${recipe.manifest}: ${error instanceof Error ? error.message : String(error)}`)
    continue
  }
  for (const field of REQUIRED) {
    if (manifest[field] === undefined) problems.push(`apps/${recipe.id}/${recipe.manifest}: "${field}" is required`)
  }
  if (manifest['assets'] !== undefined) {
    problems.push(`apps/${recipe.id}/${recipe.manifest}: "assets" is generated by prepare from the built tree -- delete it here, or it lists files from a build nobody made`)
  }
  if (manifest['entry'] !== recipe.entry) {
    problems.push(`apps/${recipe.id}: manifest entry "${String(manifest['entry'])}" and recipe entry "${recipe.entry}" disagree -- the browser loads the manifest's, the build wrapper produces the recipe's`)
  }
}

report('check:manifest', problems)
