import type { Recipe } from './recipe.ts'

// One layer above the recipe: turns each app's fake `.eth` name into what a
// resolver needs -- a name-to-port map -- without this repository or the
// shell committing to one delivery mechanism. A Chromium PAC and a plain
// name->port map are both generated from the same list, so neither
// `--proxy-pac-url` nor `--host-resolver-rules` has to be chosen here; that
// choice is verified against a real window from the shell's side. See
// docs/recipe-format.md's `eth` field and CLAUDE.md rule 9.

const ETH_NAME = /^[a-z0-9][a-z0-9-]*\.eth$/

export interface NamedApp {
  readonly name: string
  readonly port: number
}

/**
 * Every recipe with an `eth` name, in the order `loadAllRecipes` already
 * returns them (sorted by id), so the generated files are stable across
 * runs. Re-validates the name rather than trusting `parseRecipe`: this is
 * the one place a name becomes `FindProxyForURL`'s own source text, and that
 * is JavaScript Chromium executes, not a value a schema two modules away
 * merely vouched for.
 */
export function namedApps (recipes: readonly Recipe[]): NamedApp[] {
  const named: NamedApp[] = []
  for (const recipe of recipes) {
    if (recipe.eth === undefined) continue
    if (!ETH_NAME.test(recipe.eth)) {
      throw new Error(`apps/${recipe.id}: eth name "${recipe.eth}" is not one lowercase label plus ".eth"`)
    }
    named.push({ name: recipe.eth, port: recipe.port })
  }
  return named
}

/**
 * A Chromium PAC. `apps` becomes an exact-match table keyed by the lowercased
 * host `FindProxyForURL` is handed, so `notfreetube.eth` or
 * `freetube.eth.evil.com` fall through to `DIRECT` rather than matching a
 * declared name as a substring or a prefix.
 *
 * Every value is written through `JSON.stringify`, never a bare template
 * slot -- a name is already validated ASCII, but the string this function
 * returns is JAVASCRIPT SOURCE Chromium runs unmodified, which is a
 * different bar than a value merely being safe to log or store.
 */
export function generatePac (apps: readonly NamedApp[]): string {
  const entries = apps
    .map((app) => `    ${JSON.stringify(app.name)}: ${JSON.stringify(`PROXY 127.0.0.1:${String(app.port)}`)}`)
    .join(',\n')
  return `// Generated by \`orivon-port names\` -- never hand-edited, never committed.
// Steers only the fake .eth names orivon-ports declares; every other host
// reaches the network exactly as it would with no PAC configured at all.
function FindProxyForURL(url, host) {
  var apps = {
${entries}
  };
  var lower = host.toLowerCase();
  if (Object.prototype.hasOwnProperty.call(apps, lower)) return apps[lower];
  return "DIRECT";
}
`
}

/**
 * name -> port, for whichever mechanism ends up steering an app tab there --
 * a PAC, `--host-resolver-rules`, or a future replacement neither of those
 * is. Not committed; `orivon-port names` writes it into `out/`.
 */
export function generateNamesJson (apps: readonly NamedApp[]): string {
  const map: Record<string, number> = {}
  for (const app of apps) map[app.name] = app.port
  return `${JSON.stringify(map, null, 2)}\n`
}
